# Generated by Django 2.0.7 on 2018-07-26 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='text',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
        migrations.AddField(
            model_name='ticket',
            name='age',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
